### ISSUE TITLE
Is it possible to use DynamicFilters together with EntityFramework-Classic?

### ISSUE THREAD

**Issue by pilarodriguez** [zzzprojects/EntityFramework-Classic#15]
We are migrating our projects to .Net Standard. We were using EF 6 and EntityFramework.DynamicFilters.

For the migration, we replaced EF with the Z.EntityFramework.Classic (version 7.0.22) package. But we had to remove the EntityFramework.DynamicFilters package because it uses EF and we get errors using it together with Z.EntityFramework.Classic.

Is there any way to define filters in DbContext.OnModelCreating? Will the EntityFramework.DynamicFilters package be compatible with EntityFramework-Classic?

**Comment by JonathanMagnan** [comment]
Hello @pilarodriguez ,

`Entity Framework Classic` has his own filter implemented:
- Query Filter: https://entityframework-classic.net/query-filter
- Query Result Filter: https://entityframework-classic.net/query-result-filter

It's possible on your side to try it?

If you absolutely need `EntityFramework.DynamicFilters`, just let us know and we will release a new version compatible with EF Classic during the weekend.

Best Regards,

Jonathan

**Comment by pilarodriguez** [comment]
Great, thank works. Thanks you very much for the quick answer.

**Comment by JonathanMagnan** [comment]
Hello @pilarodriguez ,

Did you have the chance to try it? Let me know if everything is working as expected.

**Comment by pilarodriguez** [comment]
Yes, it works as expected. Thanks
