### ISSUE TITLE
What is the status on supporting LazyLoading?

### ISSUE THREAD

**Issue by AlirezaHaghshenas** [zzzprojects/EntityFramework-Classic#16]
Is there any plan to include support for `LazyLoading`?
What is the progress/timeline?

**Comment by AlirezaHaghshenas** [comment]
In [here](https://entityframework-classic.net/net-core), it is specifically mentioned that "Lazy loading of related data" is not supported in `.net core`.

**Comment by JonathanMagnan** [comment]
Hello @AlirezaHaghshenas ,

I believe you misread this sentence: "Here are some features in EF6 which are not supported in EF Core:".

Those feature is a list of features not yet supported in EF Core, but they are already supported in EF Classic even in .NET Core beside perharp `Migration` and `Wizard`

Lazy loading is already supported in EF Classic.

Let me know if that answer correctly to your question.

**Comment by AlirezaHaghshenas** [comment]
Aw! Thank you very much. It's great news to know we can use all these features in .net core.

BTW, The fact that I've misread this piece at least two times, suggests that many others might make the same mistake. I suggest making the docs a bit clearer. Maybe just by rephrasing this paragraph: "Here are some features in EF6 which are not supported in EF Core:"
