### ISSUE TITLE
Problem with ASP.NET and Z.EntityFramework.Classic

### ISSUE THREAD

**Issue by ARFV** [zzzprojects/EntityFramework-Classic#19]
Hi, the code generator for views in ASP.NET-MVC checks if EntityFramework is present.

![addview](https://user-images.githubusercontent.com/45031171/48472130-d61c9000-e7f5-11e8-84b0-cda5ebbfe81a.PNG)

![noentityframework](https://user-images.githubusercontent.com/45031171/48472152-e46aac00-e7f5-11e8-9b3b-8459e45dae2a.png)

![zentityeigenschaften](https://user-images.githubusercontent.com/45031171/48472162-e92f6000-e7f5-11e8-95d2-c2add91d0d92.PNG)

What can i do to solve this problem?

**Comment by JonathanMagnan** [comment]
Hello @ARFV ,

Thank you for reporting, we will look at it but I'm not sure something could be done here.

The `Wizard` expect to find an Entity Framework version, However, `EF Classic` is not a supported version for this Wizard.

We will investigate it and let you know.

Best Regards,

Jonathan

**Comment by ARFV** [comment]
Meie idea is to create a fake EntityFramework dll without content to fool VS.

**Comment by JonathanMagnan** [comment]
Hello @ARFV ,

The problem with the `fake` EntityFramework dll is that it will not be strongly named and the Wizard uses some methods of this dll.

We looked a little bit at it and I do not believe unfortunately we will be able to support it. Perharp we will try again later.

However, that doesn't remove you the ability to use this wizard, only the `Data context class` part doesn't work with our library.

Let me know if that answer correctly to this issue.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @ARFV ,

I will close this request since I don't believe anything will be done in a short-term plan about it.

Best Regards,

Jonathan
