### ISSUE TITLE
How does the licensing work?

### ISSUE THREAD

**Issue by smarts** [zzzprojects/EntityFramework-Classic#27]
This library seems to have a community (free) version, but it depends on the `Z.Expressions.Eval` package, which does not have a free version, so how does the licensing work?

**Comment by JonathanMagnan** [comment]
Hello @smarts ,

Yes, the community version is free and can be used in commercial application.

The library depends on `Z.Expressions.Eval` for supporting the [LINQ Dynamic](https://entityframework-classic.net/linq-dynamic) feature which is included in the community.

In short, a license is not required to use LINQ Dynamic. However, if you want to go beyond that and use the full potential of the library, a license will be required.

Let me know if that answer succesfully to your question.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @smarts ,

Thank you, we have added a little sentence about it "LINQ extension method is free with EF Classic - Community"

We will make it more clear when this documentation will be re-wrote.

Best Regards,

Jonathan
