### ISSUE TITLE
Error when trying to using Cache for executing a store procedure

### ISSUE THREAD

**Issue by ivantran85** [zzzprojects/EntityFramework-Classic#3]
Hi Team,
I am trying to use Cache for a result from a store procedure like this

```csharp
var employerInfo = _context.usp_get_cpr_employer_info(data.Identifier, data.PolicyId).AsQueryable().Cache().SingleOrDefault();
```

And I got an error below

System.Exception: Oops! The ObjectQuery cannot be found. Please use an explice key or report this issue here: https://github.com/zzzprojects/EntityFramework-Classic/issues
   at Z.EntityFramework.Classic.QueryCacheManager.GetCacheKey(IQueryable query)

Could you please help to fix it

Thanks so much

**Comment by JonathanMagnan** [comment]
Hello @ivantran85 ,

Adding `AsQueryable` doesn't work as that's not a context query.

However, it's possible for you to still cache this kind of query using your own cache key.

For example:

```csharp
var employerInfo = _context.usp_get_cpr_employer_info(data.Identifier, data.PolicyId).Cache("myCacheKey").SingleOrDefault();
```

Let me know if that solution work for you.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @ivantran85 ,

This issue will be closed since it has been answered.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
