### ISSUE TITLE
Enum model property support?

### ISSUE THREAD

**Issue by tiesont** [zzzprojects/EntityFramework-Classic#32]
According to Microsoft, I should be able to use automatically-mapped enum types in my model definitions: https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/data-types/enums

When using EntityFramework-Classic, the model compiles correctly, but when I attempt to load the context, I get errors similar to:

> ArgumentException: The ResultType of the specified expression is not compatible with the required type. The expression ResultType is 'MyEnumType' but the required type is 'Edm.Int32'.
> Parameter name: keyValues[0]
> 
> System.Data.Entity.Core.Common.CommandTrees.ExpressionBuilder.Internal.ArgumentValidation.RequireCompatibleType(DbExpression expression, TypeUsage requiredResultType, string argumentName, int argumentIndex)
> EntityCommandCompilationException: An error occurred while preparing the command definition. See the inner exception for details.
> 
> System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition..ctor(DbProviderFactory storeProviderFactory, DbCommandTree commandTree, DbInterceptionContext interceptionContext, IDbDependencyResolver resolver, BridgeDataReaderFactory bridgeDataReaderFactory, ColumnMapFactory columnMapFactory)

Am I missing something in the configuration of my DbContext? This is all I have in OnModelCreating:

```c#
protected override void OnModelCreating(DbModelBuilder modelBuilder)
{
    modelBuilder.Conventions.Remove<System.Data.Entity.ModelConfiguration.Conventions.PluralizingTableNameConvention>();
 }
```

I also added this to the property in question, which doesn't seem to help:

```c#
[Column("TypeID", TypeName ="int")]
public MyEnumType TypeID { get; set; }
```

My `TypeID` column _is_ a foreign key, if it's relevant.

**Comment by JonathanMagnan** [comment]
Hello @tiesont ,

Thank you for reporting, we will look at it.

Best Regards,

Jonathan

**Comment by tiesont** [comment]
Super. "Yeah, that doesn't work" is a perfectly acceptable response, by-the-way; I just need to know if it's supposed to work, and if so, how to set it up.

Thanks for the quick reply, too.

**Comment by JonathanMagnan** [comment]
Hello @tiesont ,

My developer has looked at it.

He created a Fiddle with your example: https://dotnetfiddle.net/Gnmhda

However, he is not sure about the "My TypeID column is a foreign key, if it's relevant." part.

Do you think you could show him how you are doing it?

**Comment by tiesont** [comment]
I think that's the issue, then. From that fiddle, my model would look something like

```c#
public class EntitySimple
{
	public int ID { get; set; }
	public int ColumnInt { get; set; }
	
	[Column("TypeID", TypeName = "int")]
	public MyEnumType TypeID { get; set; }
	public MyEnumDbType EntityType { get; set; }
}

public enum MyEnumType  
{
	A,
	B,
	C
}

public class MyEnumDbType
{
    public int ID { get; set; }
    public string Namne { get; set; }
}
```

Which is mostly likely the problem. I'll do some digging, but I think you've shown me what I want to do doesn't work.

**Comment by tiesont** [comment]
For what it's worth, this *does* work in EF Core, but you have to update the primary key field in the foreign key table to match the same enum and specify the database column type. So, a working version of my example would be:

```cs
public class EntitySimple
{
    [Key]
    public int ID { get; set; }
    public int ColumnInt { get; set; }
	
    [Column("TypeID", TypeName = "int")]
    public MyEnumType TypeID { get; set; }
    public MyEnumDbType EntityType { get; set; }
}

public enum MyEnumType  
{
    A = 1,
    B = 2,
    C = 3
}

public class MyEnumDbType
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    [Column(TypeName = "int")]
    public MyEnumType ID { get; set; }
    public string Name { get; set; }
}
```

The `DatabaseGeneratedOption.None` flag tells the model generator to **not** enable auto-increment on the primary key field, with the assumption that the enum table is manually maintained.
