### ISSUE TITLE
UseDatabaseFirst path handling

### ISSUE THREAD

**Issue by omski** [zzzprojects/EntityFramework-Classic#34]
The path building of the model name in UseDatabaseFirst is not platform independent and GetCurrentDirectory() is used to get the startup path which is not correct.

Please look at my changes in:
https://github.com/omski/EntityFramework-Classic/commit/79ee1cf84a3b5ded0269f7fb7c7630e1a22a6280

This way the model metadata is loaded and the corresponding files are generated too.

**Comment by JonathanMagnan** [comment]
Hello @omski ,

Thank you for reporting,

We will look at it.

Best Regards,

Jonathan

**Comment by omski** [comment]
I think this issue can be closed as it is mainly solved with v7.1.5

Thanks!
