### ISSUE TITLE
Jetbrains Rider EF 6.2 commands

### ISSUE THREAD

**Issue by maleet** [zzzprojects/EntityFramework-Classic#37]
I use Jetbrains Rider for all my C# development. They have contextmenu based EF 6.2 migration support. As EF version is detected based on referenced EF dll (I think so, no extra information provided by Jetbrains) then for Classic I don't have EF context menu.

It is more like Rider issue, but I'm not switching to Visual Studio so until EF 6.3 Classic isn't usable for me. I still can use Extensions so not big problem, but would like to use Classic. 

I created Rider issue and they can add support for Classic. Maybe I'm here the middleman and you should directly communicate with them? https://youtrack.jetbrains.com/issue/RIDER-28099

**Comment by JonathanMagnan** [comment]
I have answered on their Ticket ;)

**Comment by maleet** [comment]
Nice!

**Comment by JonathanMagnan** [comment]
We asked for a follow up on the ticket but besides following it, there is currently not a lot we can do ;(

**Comment by maleet** [comment]
I'm watching ticket also. Ef 6.3 with better command line support should make migration related tools better, but that is also far away from release. Extensions is nice alternative, but classic is already all separate libs included 😊

**Comment by maleet** [comment]
Looks like it won't happen in near future. They suggest that plugin for Rider would be one solution, but that is too much work.

**Comment by JonathanMagnan** [comment]
Yup, that's unfortunate ;(

However, we replied this morning and said that we are offering money if they make it happens.

I will keep you updated if they answer us in private.

**Comment by maleet** [comment]
EF 6.3 should resolve quite a lot with out-of-visual-studio command line support. But no release dates for EF 6.3 still... 

I don't know anything about plugin coding for Rider. If there is SDK with possibility to just toggle needed context menu selections then it shouldn't be that hard to implement. If not then... writing own window forms, execution logic aso... too much.

**Comment by maleet** [comment]
Maybe it's time to try classic again. Is classic based on ef 6.3?

**Comment by JonathanMagnan** [comment]
Hello @maleet ,

Unfortunately no, it's based on the v6.2

The v6.3 has some issues that we don't like about some query optimization they merged.

Once the v6.4 is released, if no one report any severe issue, we will merge it into our branch.

Let me know if that answer correctly to your question.

**Comment by maleet** [comment]
I need ef6.exe and commands for out of process migration management.

**Comment by maleet** [comment]
I hoped to get tool for migration management. Ef6.exe for out of process commands and also dotnet commands.

**Comment by JonathanMagnan** [comment]
Unfortunately, at this moment, we are missing time ourselves. So It's currently impossible for us to develop such tools ;(

**Comment by maleet** [comment]
I think I can use this https://github.com/mrahhal/Migrator.EF6
