### ISSUE TITLE
Use Z.EntityFramework.Plus.EF6 with Classic

### ISSUE THREAD

**Issue by pfeigl** [zzzprojects/EntityFramework-Classic#43]
Hi,

we are using EntityFramework6 in our net4x Libraries and are evaluating migrating to netstandard.
Therefor we tried migrating some of the code to EntityFramework-Classic but failed at the point where we also use EntityFramework.Plus.EF6.

Is there a way to use those two libraries together or is there plans to integrate the features of "Plus" directly into "Classic". If so, is there any timeframe? One of the first missing methods we were looking at is `DbContextExtensions.GetKeyNames`.

Thanks,
Philipp

**Comment by JonathanMagnan** [comment]
Hello @pfeigl ,

This method is only an extension that you can easily import in your project I believe: https://github.com/zzzprojects/EntityFramework-Plus/blob/29acd6b1eea9191727d915bc66c384f29f43d03a/src/shared/Z.EF.Plus._Core.Shared/EF5_EF6/DbContext/DbContext.GetKeyNames.cs

We started to import features from EF Plus into EF Classic but we didn't complete it yet. We work on it from time to time but we currently don't have any timeframe.

One alternative way for you is to use the latest version of EF6 (in preview or RC at this moment) which also finally support .NET Core and use directly EF Plus.

Let me know if that answer correctly to your question

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by pfeigl** [comment]
Hi @JonathanMagnan ,

thanks for your fast feedback. I guess for this case, integrating the code directly seems to be the most straight forward way.

We evaluated EF6.3 already, but it requires netstandard2.1 which will not be supported in any .NET Framework full version, however it is important to us, that our code can be used in .NET Framework. 

Regards,
Philipp
