### ISSUE TITLE
Type not supported yet (LazyType): sdo_geometry

### ISSUE THREAD

**Issue by jack-gaojz** [zzzprojects/EntityFramework-Classic#51]
Call the "DeleteFromQuery", the database contains the spatial data type will throw the error: Type not supported yet (LazyType): sdo_geometry.

Database: Oracle 11g.
.Net Framework 4.7
EntityFramework 6.4.
Provider: Devart.Data.Oracle

I just want to use the "DeleteFromQuery" for the entity and the entity doesn't have the geometry column, and the other data table contains.
Since the entity which just wants to delete doesn't contain the geometry column, why throw the error message? It blocks me. 

Anyone can give some suggestions? Thanks so much.

**Comment by JonathanMagnan** [comment]
Hello @jack-gaojz ,

Is this for `EF Extensions` or `EF Classic`? As you use EF 6.4, it looks more like a bug for the EF Extensions library.

This error probably happens when we read your model. Do you think you could provide your `EDMX` model? https://entityframework-extensions.net/edmx

You can send in private here: info@zzzprojects.com

We will make sure that all your types are supported.

**Comment by jack-gaojz** [comment]
@JonathanMagnan 
I used the "Z.EntityFramework.Extensions" 4.0.57. 
Ok, I will send the EDMX file.
Thanks so much.

**Comment by JonathanMagnan** [comment]
Awesome @jack-gaojz 

we will be looking forward to hearing from you ;) 

Jon

**Comment by JonathanMagnan** [comment]
Hello @jack-gaojz ,

The v4.0.59 has been finally released.

Could you try it and let us know if everything is working as expected.

We didn't updated yet the fix for `EF Classic`, so if you were really using EF Classic, let us know and we will release it as well. (If there is no v4.0.59 available that mean you are using the classic package probably)

**Comment by jack-gaojz** [comment]
Ok, thanks so much. I will try it ASAP. :)

**Comment by jack-gaojz** [comment]
> Hello @jack-gaojz ,
> 
> The v4.0.59 has been finally released.
> 
> Could you try it and let us know if everything is working as expected.
> 
> We didn't updated yet the fix for `EF Classic`, so if you were really using EF Classic, let us know and we will release it as well. (If there is no v4.0.59 available that mean you are using the classic package probably)

I have tried it, but failed.
![image](https://user-images.githubusercontent.com/40879710/77393373-dc525180-6dd7-11ea-85e9-5a925e78ff04.png)

Maybe caused by the provider(Devart.Data.Oracle) not support the bulk operations.

**Comment by JonathanMagnan** [comment]
We will look at it,

It should be supported but perhaps we are missing something for `DeleteFromQuery` method

**Comment by jack-gaojz** [comment]
Thanks so much. :)

**Comment by JonathanMagnan** [comment]
Hello @jack-gaojz ,

Sorry for the delay, I just found out that it seem we didn't answer you.

My developer and I tried to reproduce it, but none of us succeed. It seem that everything work with `Devart.Data.Oracle` so we are probably missing something.

Do you think you could provide us a project?

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jon

**Comment by jack-gaojz** [comment]
> Hello @jack-gaojz ,
> 
> Sorry for the delay, I just found out that it seem we didn't answer you.
> 
> My developer and I tried to reproduce it, but none of us succeed. It seem that everything work with `Devart.Data.Oracle` so we are probably missing something.
> 
> Do you think you could provide us a project?
> 
> _You can send it to: [info@zzzprojects.com](mailto:info@zzzprojects.com) if you need to keep the source private_
> 
> Best Regards,
> 
> Jon

I think the issue has been fixed with the latest version. Thanks so much. :)

**Comment by JonathanMagnan** [comment]
Awesome! 

we are glad everything is working out for you :)

Don't hesitate to contact us for questions, issues or feedback!

Have a good one,

Jon
