### ISSUE TITLE
IDbContext

### ISSUE THREAD

**Issue by LukeTOBrien** [zzzprojects/EntityFramework-Classic#54]
Hello,

I think an `IDbContext` would be a good thing.  
I pass my context's around using DI, so I always have an interface for each each context, but these interfaces only have the `DbSet` properties on them, and my repository isn't aware of `SubmitChanges` etc.  
An interface that contains all common `DbContext` methods would be useful.

Thanks,

Luke

**Comment by JonathanMagnan** [comment]
Hello @LukeTOBrien ,

I fail to understand how an interface `IDbContext` would give you more flexibility over the `DbContext` class? I mean you can also use class for your `DI`?

If you can give me a good reason, we would be happy to add it since that's not very hard on our side.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @LukeTOBrien 

Since our last conversation, I haven't heard from you. 

As mentioned in my previous message, would it be possible to give us further information?

Looking forward to hearing from you, 

Jon

**Comment by JonathanMagnan** [comment]
Hello again @LukeTOBrien !

A quick reminder that we are here to assist you.

don't hesitate to provide further information!

Looking forward to hearing from you,

Jon

**Comment by LukeTOBrien** [comment]
Hi there,

sorry I have a few projects on the go and I haven't been back on this.

Well I guess the issue is that I have `IXXXContext` for all my
`DbContexts`, but these interfaces only have the `Dbset` properties on
them.
So then in the repo, I call a method like`SaveChanges` that doesn't exist
on my interface, I either have to pull that method signature into my
interface or create a geneal `IDbContext` interface.
I may decide to re-write and resister the classes as services rather than
the interfaces.

I think an 'IDbContext couldn't hurt.
How do you mock DbContexts for testing without an interface?

Luke

**Comment by JonathanMagnan** [comment]
Thank you @LukeTOBrien ,

You provided a scenario in which an interface could be useful. Since an interface cannot inherit from a class, adding an interface could not be bad.

I will assign this to my developer and ask him to add the minimum information to this interface.

**Comment by LukeTOBrien** [comment]
Thank you!

**Comment by JonathanMagnan** [comment]
Hello @LukeTOBrien ,

The v7.1.27 has been released.

The `IDbContext` interface has been added. If something is missing, let us know.

Best Regards,

Jon

**Comment by LukeTOBrien** [comment]
Thank you!
