### ISSUE TITLE
EF6 is available for .NET Core 3+

### ISSUE THREAD

**Issue by teo-tsirpanis** [zzzprojects/EntityFramework-Classic#55]
This project has unfirtunately been superseded by Entity Framework 6.3 [which supports .NET Core](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-6-3-preview-with-net-core-support/).

**Comment by JonathanMagnan** [comment]
Hello @teo-tsirpanis ,

Yup, you are right. EF 6 now support .NET Core.

However, our library still has some integrated features which is not available in EF6: https://entityframework-classic.net/features and is the only one supporting .NET Standard 2.0

That's up to you to choose which one you want to use.

Best Regards,

Jon
