### ISSUE TITLE
Make DbMigrator constructors public

### ISSUE THREAD

**Issue by schuettecarsten** [zzzprojects/EntityFramework-Classic#57]
Please make the following internal constructor of DbMigrator public - as it is in EF6:

```
    internal DbMigrator(DbMigrationsConfiguration configuration, DbContext usersContext)
```

**Comment by JonathanMagnan** [comment]
Sure, it will be done for the next release unless it causes some conflict

**Comment by JonathanMagnan** [comment]
Hello @schuettecarsten ,

The v7.1.30 has been released.

The DbMigrator constructor is now public.

Let me know if everything works as expected.

Best Regards,

Jon

**Comment by schuettecarsten** [comment]
Hi,

I juts upgraded to v7.1.30 but still get the error:

```
var migrator = new DbMigrator(configuration, dbContext);
```
```
error CS1729: 'DbMigrator' does not contain a constructor that takes 2 arguments
```

**Comment by JonathanMagnan** [comment]
You are right!

Look like I forget one important step when merging the branch... ;)

The v7.1.31 has been released.

Let me know if everything works as expected.
