### ISSUE TITLE
Link to entityframework.net

### ISSUE THREAD

**Issue by LukeTOBrien** [zzzprojects/EntityFramework-Classic#58]
I am converting a legacy app to .Net Core and I was just searching on how to call a Stored Procedure and [I found the answer here](https://entityframework.net/articles/carloscds-ef6-stored-procedure).  
But I noticed that you don't have a link to https://entityframework.net/ on your EF Classic website - So I would like to suggest this, it is a great documentation site and applies to EFC as well.

Also since Microsoft have moved on from EF6, I think you should primarily document your own product, perhaps consolidate your documentation into a sub-domain rather than pay for the extra domain?

**Comment by JonathanMagnan** [comment]
Hello @LukeTOBrien ,

Thank you for your suggestion, we will discuss about it to see what we will do, but we will surely add a link as you suggested ;)

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @LukeTOBrien ,

We added a "Related" section on the right side (for Desktop). We added 3 links, EF Documentation, EF Extensions and C# Eval Expression

This is pretty light but at this moment, we don't want to make it to big either.

We discussed about it and we don't want to consolidate both documentation. We prefer to keep them separated even if they are very linked.

**Comment by LukeTOBrien** [comment]
Thanks for the update.  
I'm glad you discussed this and the links are good :-)

Luke
