### ISSUE TITLE
InvalidOperationException when using .Future() within a transaction

### ISSUE THREAD

**Issue by neoGeneva** [zzzprojects/EntityFramework-Classic#6]
When attempting to use `.Future()` and `QueryFutureEnumerable.ToListAsync()` within a transaction I get the following exception:

```
InvalidOperationException: BeginExecuteReader requires the command to have a transaction when the connection assigned to the command is in a pending local transaction. The Transaction property of the command has not been initialized.
  System.Data.SqlClient.SqlCommand+<>c.<ExecuteDbDataReaderAsync>b__122_0(Task<SqlDataReader> result)
  System.Threading.Tasks.ContinuationResultTaskFromResultTask<TAntecedentResult, TResult>.InnerInvoke()
  System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, object state)
  System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref Task currentTaskSlot)
  .(CancellationToken cancellationToken)
  Z.EntityFramework.Classic.QueryFutureBatch.ExecuteQueriesAsync(CancellationToken cancellationToken)
  Z.EntityFramework.Classic.QueryFutureEnumerable<T>.ToListAsync(CancellationToken cancellationToken)
  ...
```

Version: Z.EntityFramework.Classic 7.0.12
OS: Windows 10
TargetFramework: netcoreapp2.1

**Comment by JonathanMagnan** [comment]
Hello @neoGeneva ,

Thank a lot, we will try it on our side.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @neoGeneva ,

The v7.0.13 has been released.

The library should now honor the transaction if one is started.

Let me know if that issue is fixed on your side.

Best Regards,

Jonathan

**Comment by neoGeneva** [comment]
Hey, I just got the latest release and the fix works great, thanks!
