### ISSUE TITLE
Error when using UpdateFromQuery on an expanded query (Linqkit)

### ISSUE THREAD

**Issue by shtifanov** [zzzprojects/EntityFramework-Classic#61]
Hi,

we have noticed that the UpdateFromQuery()/DeleteFromQuery() methods does not work with an expanded query.
I've created a small runnable example where this problem can be reproduced.

```
private static Expression<Func<Customer, bool>> _testFilterExpression = c => c.Name == "abc";

public static void Main(string[] args)
{

	try
	{
		var ctx = new TestContext();
		var simpleRequest = ctx.Customers.Count();
		
		// this works
		var batchUpdate = ctx.Customers
			.Where(c => c.Name == "abc")
			.UpdateFromQuery(c => new Customer { Name = "Test" });
		
		// this crushes
		var batchLinqKitUpdate = ctx.Customers
			.AsExpandable()
			.Where(c => _testFilterExpression.Invoke(c) && c.Id > 0)
			.UpdateFromQuery(c => new Customer { Name = "Test" });
	}
	catch (Exception e)
	{
		
	}
}
```

> System.Exception: Could not find the context from the IQueryable expression. Are you sure this is coming from an Entity Framework Context?
>    at .[](IQueryable`1 )
>    at DbContextExtensions.[](IQueryable`1 , Expression`1 , Action`1 , Boolean )
>    at DbContextExtensions.Update
[efClassicAndLinqKit.zip](https://github.com/zzzprojects/EntityFramework-Classic/files/5354759/efClassicAndLinqKit.zip)
FromQuery[TEntity](IQueryable`1 query, Expression`1 updateExpression, Action`1 bulkOperationFactory)
>    at DbContextExtensions.UpdateFromQuery[TEntity](IQueryable`1 query, Expression`1 updateExpression)
>    at ConsoleApp.Program.Main(String[] args) in C:\dev\test_projects\efClassicAndLinqKit\ConsoleApp\Program.cs:line 28

Maybe you can give me a hint, what is wrong here?

I'm using 
Z.EntityFramework.Classic 7.1.34
LinqKit.Z.EntityFramework.Classic 1.1.17
[efClassicAndLinqKit.zip](https://github.com/zzzprojects/EntityFramework-Classic/files/5354771/efClassicAndLinqKit.zip)

**Comment by JonathanMagnan** [comment]
Hello @shtifanov ,

I'm not sure if we will succeed to make it works but we will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @shtifanov ,

Sorry for the long waiting,

The v7.1.36 has been released.

Let me know if it's now working correctly with LinqKit.

Best Regards,

Jon

**Comment by shtifanov** [comment]
Hello @JonathanMagnan ,
it seems to work. Thank you for your effort!
