### ISSUE TITLE
Saving with a DB error results in Secure binary serialization is not supported on this platform

### ISSUE THREAD

**Issue by rogerfar** [zzzprojects/EntityFramework-Classic#9]
I'm doing a SaveChanges on an object which contains an error (invalid reference to a FK object), but instead of throwing the actual error it throws:

`System.PlatformNotSupportedException: 'Secure binary serialization is not supported on this platform.`

If I change my SaveChanges in await SaveChangesAsync it swallows the error and hangs forever.

This is on the latest version with a .NET Core 2.1 project.

Stacktrace:

   at System.Exception.add_SerializeObjectState(EventHandler`1 value)
   at System.Data.Entity.Internal.InternalContext.WrapUpdateException(UpdateException updateException)
   at System.Data.Entity.Internal.InternalContext.SaveChanges()

**Comment by JonathanMagnan** [comment]
Hello @farlock85 ,

Thank a lot for reporting, we should look at it within a few hours to try to reproduce it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @farlock85 ,

The v7.0.14 has been released.

The issue was caused because `.NET Core` has dropped the support of some binary serialization object that was previously supported in the `.NET Framework`.

Let me know if everything works as expected.

Best Regards,

Jonathan
